:sparkles: 개선
Signed-off-by: JHKoder <jeonghun.kang.dev@gmail.com>

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -102,7 +102,12 @@ jobs:
         run: |
           date=$(date +'%Y%m%d-%H%M%S')
           TARGET_JAR=$(find build/libs -name "*.jar" -print -quit)
+            if [ -z "$TARGET_JAR" ]; then
+            echo "JAR file not found in build/libs directory"
+              exit 1
+            fi
 
+  
           echo "Backing up old JAR file on remote server..."
           ssh -i $SSH_KEY $REMOTE_USER@${{ secrets.APP_SERVER_IP }}  "mkdir -p $BACKUP_DIR"
           ssh -i $SSH_KEY $REMOTE_USER@${{ secrets.APP_SERVER_IP }}  "if [ -f /home/ubuntu/dev/server.jar ]; then mv /home/ubuntu/dev/server.jar $BACKUP_DIR/server-$date.jar; fi"
